steps:
- name: 'python:3.11'
  entrypoint: pip
  args: ['install', '--upgrade', 'pip']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/software-engineering-457116/carbon-credit-app', '.']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/software-engineering-457116/carbon-credit-app']
  
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gcloud', 'run', 'deploy', 'carbon-credit-app',
         '--image', 'gcr.io/software-engineering-457116/carbon-credit-app',
         '--platform', 'managed',
         '--region', 'us-central1',
         '--allow-unauthenticated',
         '--add-cloudsql-instances', '${_INSTANCE_CONNECTION_NAME}',
         '--set-env-vars', 'SECRET_KEY=${_SECRET_KEY},INSTANCE_CONNECTION_NAME=${_INSTANCE_CONNECTION_NAME},DB_USER=${_DB_USER},DB_PASS=${_DB_PASS},DB_NAME=${_DB_NAME}']
images:
- 'gcr.io/software-engineering-457116/carbon-credit-app'