substitutions:
  _SECRET_KEY: "013eef93b518082e667c7578a0220857973d3374123bd5043ceb8a3334c160d5"
  _INSTANCE_CONNECTION_NAME: "software-engineering-457116:us-central1:carboncred"
  _DB_USER: "postgres"
  _DB_PASS: "CarbonCred@123"
  _DB_NAME: "carbon_credits"

steps:
# Optional: Upgrade pip (not always needed)
- name: 'python:3.11'
  entrypoint: pip
  args: ['install', '--upgrade', 'pip']

# Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/software-engineering-457116/carbon-credit-app', '.']

# Push Docker image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/software-engineering-457116/carbon-credit-app']

# Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
    - 'gcloud'
    - 'run'
    - 'deploy'
    - 'carbon-credit-app'
    - '--image'
    - 'gcr.io/software-engineering-457116/carbon-credit-app'
    - '--platform'
    - 'managed'
    - '--region'
    - 'us-central1'
    - '--allow-unauthenticated'
    - '--add-cloudsql-instances'
    - '${_INSTANCE_CONNECTION_NAME}'
    - '--set-env-vars'
    - |
      SECRET_KEY=${_SECRET_KEY},
      INSTANCE_CONNECTION_NAME=${_INSTANCE_CONNECTION_NAME},
      DB_USER=${_DB_USER},
      DB_PASS=${_DB_PASS},
      DB_NAME=${_DB_NAME},
      DATABASE_URL=postgresql+pg8000://${_DB_USER}:${_DB_PASS}@34.59.6.90:5432/${_DB_NAME}

images:
  - 'gcr.io/software-engineering-457116/carbon-credit-app'
